apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ct-server-0-6@sha256:a4fc307ee4e5d987b6978edc4849b2008e218d2cd3ac7f163abc8798c3ec0e07
        name: my-go
        resources: {}
status: {}
