apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ct-server-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ct-server-0-6@sha256:ba0fdba6e5e5ee3a96dd7ba2e84b142904f3a77568d3a7ab48636817ee3484a6
        name: my-go
        resources: {}
status: {}
