apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ctlog-managectroots-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ctlog-managectroots-0-6@sha256:debbee87cd54e95ff95a4281a634f2c9a2dfbcfb15bf36979f861b36e0eccbf6
        name: my-go
        resources: {}
status: {}
