apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ctlog-verify-fulcio-0-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctlog-verify-fulcio-0-6
    app.kubernetes.io/part-of: scaffold-1-0-gamma
  name: ctlog-verify-fulcio-0-6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: ctlog-verify-fulcio-0-6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: ctlog-verify-fulcio-0-6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ctlog-verify-fulcio-0-6@sha256:962e7d522f9d6de3f6fd3619bb55e6f3cc2d3200efccdc2cf8139146cf576b5d
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
