apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ctlog-verify-fulcio-0-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ctlog-verify-fulcio-0-6
    app.kubernetes.io/part-of: scaffold-1-0-gamma
  name: ctlog-verify-fulcio-0-6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: ctlog-verify-fulcio-0-6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: ctlog-verify-fulcio-0-6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ctlog-verify-fulcio-0-6@sha256:d11314c983f9c65f251ce4ce99dae321836988ef4ac7446f765496d60e23343b
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
