apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: creatctconfig-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/creatctconfig-0-6@sha256:ca56397a9ec9e13061ba7f95640d58a95859d26bf3b6c72f536dfeca5d3d297a
        name: my-go
        resources: {}
status: {}
