apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: creatctconfig-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/creatctconfig-0-6@sha256:52a7cca29afd141f91ced8bb9037a07ccbec0c725d4d0f0843207aa04cb121b1
        name: my-go
        resources: {}
status: {}
