apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tuf-server-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/tuf-server-0-6@sha256:79310dfb60fd9230a3d4880c9219581373ceca4ec88d6aa3d7921c5e4a15ee72
        name: my-go
        resources: {}
status: {}
