apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createctconfig-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/createctconfig-0-6@sha256:2c96132697025f91dfdfd6b4d2376b9d6fb3231192647e9abcbf8239e8121c0d
        name: my-go
        resources: {}
status: {}
