apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createctconfig-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/createctconfig-0-6@sha256:e55ac61a58aea6ca7ac69ebadcb00dfe0773f0fa5d1db4633297310080b44000
        name: my-go
        resources: {}
status: {}
