apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: createctconfig-0-6
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/createctconfig-0-6@sha256:2648bc88cf6cfe2369b8ef3daa0150d19a80303351478eda3de897939f0af373
        name: my-go
        resources: {}
status: {}
