apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tuf-server-1-0-gamma
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/tuf-server-1-0-gamma@sha256:0926de72518eee7e5eb47152d43106873fd786907016709ccb990053b98f7ddf
        name: my-go
        resources: {}
status: {}
