apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ctlog-verify-fulcio-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ctlog-verify-fulcio-0-6@sha256:22bab2e8d99de4542dec3dffe19b07d61692c3ed64125f79058a566f6dc5c6e2
        name: my-go
        resources: {}
status: {}
