apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ctlog-verify-fulcio-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ctlog-verify-fulcio-0-6@sha256:64910ee1ba97b154166116475d21f98f3639500bbba7365cc1393828cb5d9935
        name: my-go
        resources: {}
status: {}
