apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ctlog-verify-fulcio-0-6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/ctlog-verify-fulcio-0-6@sha256:d672ded5390bf9dfcd39584a06995bf2b6359e8a71f1c74f1a5cc192c31b670e
        name: my-go
        resources: {}
status: {}
