apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: createctconfig-0-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: createctconfig-0-6
    app.kubernetes.io/part-of: scaffold-1-0-gamma
  name: createctconfig-0-6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: createctconfig-0-6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: createctconfig-0-6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/scaffold-1-0-gamma/createctconfig-0-6@sha256:63bc1f98269568f2ba4aed0cd75c10485327e8dee93fcd80a53797d223d36ec1
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
